#ifndef VALENTINEASSEMBLER_INSTRUCTIONLIBRARY_HPP
#define VALENTINEASSEMBLER_INSTRUCTIONLIBRARY_HPP

#include "../BRA.hpp"
#include "../MOV.hpp"
#include "../LOD.hpp"

#endif //VALENTINEASSEMBLER_INSTRUCTIONLIBRARY_HPP
